#!/usr/bin/env python3
"""Cut the offline suite's fixtures out of real captures, and PROVE they parse
the same.

Its output is `fixtures_generated.json`, which `smoke_test.py` loads.

WHY A GENERATED FILE RATHER THAN INLINE LITERALS
------------------------------------------------
The family's rule is fixtures inline in `smoke_test.py`, and on most of these
sites that works because a fixture is a few hundred bytes of markup. Here the
fixture IS the server-rendered payload: one `AF_initDataCallback` blob is
4-240 KB of nested JSON, and a fixture has to carry whole blobs or it stops
exercising anything the parser is built on. Pasting that into a Python source
file as string literals would make `smoke_test.py` unreadable. The generated
JSON sits beside it, is regenerated by this script, and is checked by the
suite for the same properties inline fixtures would be.

WHAT YOU NEED TO RUN IT
-----------------------
Your own captures, in `captures/` relative to the repo, named as the SOURCES
table below expects. They are deliberately NOT in the repository: one capture
of this site is 0.6-1.4 MB and eleven of them is 13 MB.

Take them with `--dump-html`, which writes exactly the bytes the parser was
given, or with curl AND A BROWSER USER-AGENT — curl's own User-Agent is
redirected to /finance/beta/unsupported and captures a page with no data in
it at all, which is a useful fixture but not the one you meant to take.

HOW THE TRIM IS CHOSEN
----------------------
Greedily, smallest blob first, keeping a blob only if it contributes rows no
already-kept blob produced. That is not an optimisation for its own sake: the
root page publishes its indices strip TWICE under two keys with identical
content, and the second copy is 241 KB against the first's 11 KB. A naive
"keep every blob that yields rows" trim was measured at 258 KB for a fixture
that a 17 KB one covers row for row.

WHAT IT ENFORCES, and why each rule is here
-------------------------------------------
  * every fixture is CUT from a real capture, never hand-written;
  * each one is verified to parse IDENTICALLY to the untrimmed original —
    every column of every row, not a sample of them. A trim that dropped the
    blob carrying a currency would silently empty that column, and a suite
    built on it would then assert the emptiness as correct;
  * the two state fixtures (Page Not Found, unsupported browser) keep their
    MARKER and are verified to classify the same way the full page does;
  * nothing credential-shaped survives into the output. Google Finance
    embeds no user session in these pages — the captures are anonymous — but
    the check runs anyway and reports what it replaced, because the day a
    capture is taken from a signed-in browser is not the day to discover the
    scrubber was never written.
"""

from __future__ import annotations

import json
import os
import re
import sys
from typing import Dict, List, Optional, Tuple

import product_parser as pp

REPO_ROOT = os.path.dirname(os.path.abspath(__file__))
CAPTURES = os.path.join(REPO_ROOT, "captures")
OUT_PATH = os.path.join(REPO_ROOT, "fixtures_generated.json")

_AF_BLOB = re.compile(r"AF_initDataCallback\(\{.*?\}\);", re.S)

# name -> (capture file, mode, url it was fetched as)
SOURCES: Dict[str, Tuple[str, str, str]] = {
    "quote_stock_us": ("quote_stock_us.html", "quote",
                       "https://www.google.com/finance/beta/quote/GOOGL:NASDAQ"),
    "quote_stock_de": ("quote_stock_de.html", "quote",
                       "https://www.google.com/finance/beta/quote/BMW:ETR"),
    "quote_index": ("quote_index.html", "quote",
                    "https://www.google.com/finance/beta/quote/.INX:INDEXSP"),
    "quote_currency": ("quote_currency.html", "quote",
                       "https://www.google.com/finance/beta/quote/EUR-USD"),
    "quote_crypto": ("quote_crypto.html", "quote",
                     "https://www.google.com/finance/beta/quote/BTC-USD"),
    "quote_futures": ("quote_futures.html", "quote",
                      "https://www.google.com/finance/beta/quote/GCW00:COMEX"),
    "markets_us": ("markets_us.html", "markets",
                   "https://www.google.com/finance/beta/?hl=en&gl=US"),
    "markets_de": ("markets_de.html", "markets",
                   "https://www.google.com/finance/beta/?hl=de&gl=DE"),
    "movers_us": ("markets_us.html", "movers",
                  "https://www.google.com/finance/beta/?hl=en&gl=US"),
    "movers_de": ("markets_de.html", "movers",
                  "https://www.google.com/finance/beta/?hl=de&gl=DE"),
}

# Fixtures that exist to exercise a STATE rather than a row. They keep the
# marker and as little else as will still classify.
STATE_SOURCES: Dict[str, Tuple[str, str, str, str]] = {
    "not_found": ("quote_notfound.html", "quote",
                  "https://www.google.com/finance/beta/quote/ZZZZQQ:NASDAQ",
                  "not_found"),
    "unsupported_browser": ("unsupported_browser.html", "quote",
                            "https://www.google.com/finance/beta/quote/GOOGL:NASDAQ",
                            "unsupported_client"),
}

# Patterns, not literals. Guarding with the values one capture happened to
# contain is how the next capture ships unscrubbed (CLAUDE.md §10).
SECRET_PATTERNS = (
    (re.compile(r'\b[A-Fa-f0-9]{32}\b'), "<32-HEX-REDACTED>"),
    (re.compile(r'(SAPISID|SSID|HSID|SID|APISID)=[^;"\s]+'), r"\1=<REDACTED>"),
    (re.compile(r'"(access_token|id_token|apiKey|api_key)"\s*:\s*"[^"]+"'),
     r'"\1":"<REDACTED>"'),
    (re.compile(r'\\"(access_token|id_token|apiKey|api_key)\\"\s*:\s*\\"[^"]*?\\"'),
     r'\\"\1\\":\\"<REDACTED>\\"'),
)


def _document(parts: List[str]) -> str:
    """A minimal HTML document carrying `parts`.

    Deliberately not a bare concatenation: `detect_page_state` runs
    `served_by_google`, which counts the site's own asset host, so a fixture
    with no asset reference at all would classify as `unknown` and every
    state assertion built on it would be testing the wrong thing.
    """
    return ('<!doctype html><html><head>'
            '<link rel="stylesheet" href="https://www.gstatic.com/finance/x.css">'
            '<script src="https://www.gstatic.com/finance/x.js"></script>'
            '</head><body>' + "".join(parts) + '</body></html>')


def _rows_signature(rows) -> List[dict]:
    """Every column of every row, minus the two that move between parses."""
    import dataclasses
    out = []
    for r in rows:
        d = dataclasses.asdict(r)
        d.pop("scraped_at", None)
        out.append(d)
    return out


def _minimal_blobs(html: str, url: str, mode: str) -> Tuple[List[str], List[str]]:
    """The smallest set of blobs that reproduces the full parse.

    Greedy, smallest first — see the module docstring for why the order
    matters by a factor of fifteen.
    """
    blobs = _AF_BLOB.findall(html)
    scored = sorted(blobs, key=len)
    kept: List[str] = []
    seen_rows: set = set()
    for blob in scored:
        rows = pp.parse_products(_document([blob]), url, mode=mode)
        keys = {(r.sku, r.listing) for r in rows}
        if keys - seen_rows:
            kept.append(blob)
            seen_rows |= keys
    # Restore the capture's own order: the parser must not depend on it, and
    # a fixture that silently reordered the payload would hide it if it did.
    order = {id(b): i for i, b in enumerate(blobs)}
    kept.sort(key=lambda b: order[id(b)])
    return kept, blobs


def _scrub(text: str) -> Tuple[str, List[str]]:
    hits: List[str] = []
    for pattern, repl in SECRET_PATTERNS:
        if pattern.search(text):
            hits.append(pattern.pattern)
            text = pattern.sub(repl, text)
    return text, hits


def build() -> int:
    if not os.path.isdir(CAPTURES):
        print("No captures/ directory. See this file's docstring for how to "
              "take one.", file=sys.stderr)
        return 2

    fixtures: Dict[str, dict] = {}
    failures = 0

    for name, (filename, mode, url) in SOURCES.items():
        path = os.path.join(CAPTURES, filename)
        if not os.path.exists(path):
            print(f"  {name}: SKIP, no {filename}")
            continue
        html = open(path, encoding="utf-8", errors="replace").read()
        expected = _rows_signature(pp.parse_products(html, url, mode=mode))
        kept, all_blobs = _minimal_blobs(html, url, mode)
        doc = _document(kept)
        got = _rows_signature(pp.parse_products(doc, url, mode=mode))
        if got != expected:
            print(f"  {name}: FAIL — trimmed fixture parses differently "
                  f"({len(got)} rows vs {len(expected)})")
            failures += 1
            continue
        doc, hits = _scrub(doc)
        if hits:
            print(f"  {name}: scrubbed {len(hits)} pattern(s): {hits}")
            if _rows_signature(pp.parse_products(doc, url, mode=mode)) != expected:
                print(f"  {name}: FAIL — scrubbing changed the parse")
                failures += 1
                continue
        fixtures[name] = {
            "mode": mode,
            "url": url,
            "html": doc,
            "rows": expected,
            "source_capture": filename,
            "blobs_kept": len(kept),
            "blobs_in_capture": len(all_blobs),
            "capture_bytes": len(html),
        }
        print(f"  {name}: {len(expected):3d} rows, {len(doc):>7,} bytes "
              f"({len(kept)}/{len(all_blobs)} blobs, "
              f"{len(doc) * 100 // max(len(html), 1)}% of the capture)")

    for name, (filename, mode, url, expected_state) in STATE_SOURCES.items():
        path = os.path.join(CAPTURES, filename)
        if not os.path.exists(path):
            print(f"  {name}: SKIP, no {filename}")
            continue
        html = open(path, encoding="utf-8", errors="replace").read()
        full_state = pp.detect_page_state(html, 200, url, mode)
        if full_state != expected_state:
            print(f"  {name}: FAIL — the CAPTURE classifies as {full_state!r}, "
                  f"not {expected_state!r}. The capture is wrong, not the "
                  f"expectation.")
            failures += 1
            continue
        markers = (pp.NOT_FOUND_MARKERS if expected_state == "not_found"
                   else pp.UNSUPPORTED_MARKERS)
        present = [m for m in markers if m in html]
        doc = _document(['<div data-fixture="%s">%s</div>'
                         % (name, "".join(present))])
        doc, hits = _scrub(doc)
        got = pp.detect_page_state(doc, 200, url, mode)
        if got != expected_state:
            print(f"  {name}: FAIL — trimmed fixture classifies as {got!r}")
            failures += 1
            continue
        fixtures[name] = {
            "mode": mode,
            "url": url,
            "html": doc,
            "state": expected_state,
            "markers_present": present,
            "source_capture": filename,
            "capture_bytes": len(html),
        }
        print(f"  {name}: state={expected_state}, {len(doc):,} bytes, "
              f"{len(present)} marker(s)")

    if failures:
        print(f"\n{failures} fixture(s) failed verification — nothing written.",
              file=sys.stderr)
        return 1

    payload = {
        "_README": (
            "Generated by make_fixtures.py from real captures. Do not edit by "
            "hand: every fixture here is verified to parse identically to the "
            "capture it was cut from, and a hand edit silently breaks that "
            "guarantee. Regenerate instead."),
        "fixtures": fixtures,
    }
    with open(OUT_PATH, "w", encoding="utf-8") as f:
        json.dump(payload, f, ensure_ascii=False, indent=1, sort_keys=True)
    total = sum(len(v["html"]) for v in fixtures.values())
    print(f"\nWrote {len(fixtures)} fixtures -> {OUT_PATH} ({total:,} bytes)")
    return 0


if __name__ == "__main__":
    sys.exit(build())
